### ISSUE TITLE
Identify and update data author and contributor information

### ISSUE THREAD

**Issue by mianzg** [openwashdata/watercostaccra#1]
Hi, the current data package include you and our package developer as the authors.

Please provide **all other data authors/contributors** for this dataset if you are aware of. Reply with the format:

First Name:
Family Name:
Email:
ORCiD (if available):

**Comment by efvicario** [comment]
Hello,

Betty is the other author of the data, and the data collection was supervised by Dr. Amankwaa. See below:

First Name: Betty Avanu
Family Name: Davidson
Email: badavidson@st.ug.edu.gh
ORCiD (if available): 0009-0006-9594-4048

First Name: Ebenezer F.
Family Name: Amankwaa
Email: efamankwaa@ug.edu.gh
ORCiD (if available): 0000-0002-8735-2521

Thanks,
Elizabeth

**Comment by mianzg** [comment]
@efvicario Thanks I updated the author information accordingly.
