### ISSUE TITLE
Review README and website content

### ISSUE THREAD

**Issue by mianzg** [openwashdata/watercostaccra#3]
@efvicario Hello, the last part before releasing the package is to review the content of README and the website. Please let me know if you would like to change any writing parts, add more links, or have any questions.

The citation information will be fixed after the release. 

Like dictionary, I also encourage you to make changes on `README.Rmd` by yourself. I am happy to provide assistance here.

**Comment by efvicario** [comment]
Hi @mianzg 

Sorry for the delay, I missed this post. 
There are some edits here for the introduction for the readme file, I have reuploaded it. Please let me know if I can look over anything else!
Elizabeth

**Comment by efvicario** [comment]
Hi, anything I can do to move publishing along? I want to link to this dataset in a paper that I'm about to submit. Thanks

**Comment by mianzg** [comment]
@efvicario Thanks for reaching out. I will wrap up and make a release for the data package by this Sunday. Does it work for you?

**Comment by efvicario** [comment]
Hi @mianzg , thank you! Much appreciated.

**Comment by efvicario** [comment]
Hi @mianzg, I can cite the package now I see, was it Götschmann et al before and now I am the first author? Let me know if it's correct so I can cite the placeholder! Thanks

**Comment by larnsce** [comment]
Hi @efvicario, I will take over from @mianzg. I will work on fixing the citation information

**Comment by larnsce** [comment]
Citation is fixed and website updated. All covered in the following Pull Request which I have already merged into main: https://github.com/openwashdata/watercostaccra/pull/7
